import { readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join } from "path";
import { inferToolMetadata, resolveToolIndexFile } from "./toolMetadata";
import { tools as registeredTools, type Tool, type ToolType } from "../tools/tools.index";

export interface ScannedTool {
  id: string;
  type: ToolType;
  path: string;
  filePath: string;
}

export interface EnrichedTool extends Tool {
  autoDetected?: boolean;
  filePath?: string;
  date?: number;
}

export function scanTools(toolsDir: string) {
  const results: ScannedTool[] = [];

  for (const type of ["html", "react"] as const) {
    const typeDir = join(toolsDir, type);
    let entries: string[];
    try {
      entries = readdirSync(typeDir);
    } catch {
      continue;
    }

    for (const entry of entries) {
      if (entry.startsWith("_")) continue;

      const fullPath = join(typeDir, entry);
      const stat = statSync(fullPath);

      if (stat.isDirectory()) {
        let childFiles: string[];
        try {
          childFiles = readdirSync(fullPath);
        } catch {
          continue;
        }

        const indexFile = resolveToolIndexFile(type, childFiles);
        if (!indexFile) continue;

        results.push({
          id: entry,
          type,
          path: `${type}/${entry}`,
          filePath: `${type}/${entry}/${indexFile}`,
        });
      } else if (stat.isFile()) {
        if (type === "html" && entry.endsWith(".html")) {
          const id = entry.replace(/\.html$/, "");
          results.push({
            id,
            type,
            path: `html/${id}`,
            filePath: `html/${entry}`,
          });
        } else if (type === "react" && /\.(tsx|jsx)$/.test(entry)) {
          const id = entry.replace(/\.(tsx|jsx)$/, "");
          results.push({
            id,
            type,
            path: `react/${id}`,
            filePath: `react/${entry}`,
          });
        }
      }
    }
  }

  return results;
}

export function generateAutoRegistry(toolsDir: string) {
  const scanned = scanTools(toolsDir);
  const registeredIds = new Set(registeredTools.map((tool) => `${tool.type}:${tool.id}`));
  const allTools: EnrichedTool[] = [];
  const reactComponentsLines: string[] = [];

  for (const tool of registeredTools) {
    const match = scanned.find((candidate) => candidate.id === tool.id && candidate.type === tool.type);
    const filePath = match ? match.filePath : tool.type === "html" ? `html/${tool.id}/index.html` : `react/${tool.id}/index.tsx`;
    const date = getMtime(toolsDir, filePath);

    allTools.push({
      ...tool,
      filePath,
      date,
    });

    if (tool.type === "react") {
      reactComponentsLines.push(`  "${tool.path}": lazy(() => import("./${filePath}")),`);
    }
  }

  for (const entry of scanned) {
    if (registeredIds.has(`${entry.type}:${entry.id}`)) continue;

    const source = readToolSource(toolsDir, entry.filePath);
    const metadata = inferToolMetadata({ id: entry.id, type: entry.type, source });
    const inferred: EnrichedTool = {
      id: entry.id,
      ...metadata,
      type: entry.type,
      path: entry.path,
      autoDetected: true,
      filePath: entry.filePath,
      date: getMtime(toolsDir, entry.filePath),
    };

    allTools.push(inferred);

    if (entry.type === "react") {
      reactComponentsLines.push(`  "${entry.path}": lazy(() => import("./${entry.filePath}")),`);
    }
  }

  const content = `// =========================================================
// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by the build/dev server (src/lib/toolRegistry.ts).
// =========================================================
import { lazy } from "react";
import type { Tool } from "./tools.index";

export interface EnrichedTool extends Tool {
  autoDetected?: boolean;
  filePath?: string;
  date?: number;
}

export const tools: EnrichedTool[] = ${JSON.stringify(allTools, null, 2)};

export const reactComponents: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
${reactComponentsLines.join("\n")}
};
`;

  writeFileSync(join(toolsDir, "auto-registry.tsx"), content, "utf8");
  return allTools;
}

function getMtime(toolsDir: string, filePath: string) {
  try {
    return statSync(join(toolsDir, filePath)).mtimeMs;
  } catch {
    return Date.now();
  }
}

function readToolSource(toolsDir: string, filePath: string) {
  try {
    return readFileSync(join(toolsDir, filePath), "utf8").slice(0, 120_000);
  } catch {
    return "";
  }
}
